source 'https://github.com/CocoaPods/Specs.git'

# Khai báo source Ali Spec
source 'https://github.com/Ali-Corp/PodSpecs.git'

platform :ios, '14.0'
use_frameworks!

target 'ALIOTTExample' do
  pod 'ALIOTT', '~> 1.0.10'
  pod 'Starscream', '~> 3.1'

  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
      end
    end
  end
end
